DROP TABLE IF EXISTS pearls_to_classes;

CREATE TABLE pearls_to_classes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pearl_name TEXT NOT NULL,
    class_name TEXT NOT NULL,
    weight INTEGER NOT NULL
);

CREATE TABLE concepts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    concept_name TEXT NOT NULL
);

CREATE TABLE classes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    class_name TEXT NOT NULL
);

CREATE TABLE concepts_to_classes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    concept_name TEXT NOT NULL,
    class_name TEXT NOT NULL
);


CREATE TABLE contents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content_name TEXT NOT NULL
);

CREATE TABLE contents_to_concepts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content_name TEXT NOT NULL,
    concept_name TEXT NOT NULL
);